name: Build test

on:
  pull_request:

env:
  POKY_URL: http://git.yoctoproject.org/git/poky
  DISTRO: poky
  HOST: ubuntu-20.04

jobs:
  meta-qcom-premerge-build-test:
    name: Premerge build test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machines: [dragonboard410c, qrb5165-rb5, sa8155p-adp]
        tclibc: [glibc, musl]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade tuxsuite
    - name: Setup tux definition
      env:
        MACHINE: ${{ matrix.machines }}
        TCLIBC: ${{ matrix.tclibc }}
      run: |
        cat << EOF > tux.json
        {
          "sources": {
            "git_trees": [
              {
                "url": "$POKY_URL",
                "branch": "$GITHUB_BASE_REF"
              },
              {
                "url": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY",
                "ref": "$GITHUB_REF"
              }
            ]
          },
          "container": "$HOST",
          "envsetup": "poky/oe-init-build-env",
          "distro": "$DISTRO",
          "machine": "$MACHINE",
          "target": "core-image-minimal",
          "bblayers_conf": [
            "BBLAYERS += '../meta-qcom-test/'"
          ],
          "artifacts": [
            "\$DEPLOY_DIR"
          ],
            "environment": {
          },
          "local_conf": [
            "INHERIT += 'buildstats buildstats-summary'",
            "TCLIBC := '$TCLIBC'"
          ]
        }
        EOF
    - name: Run build
      run: |
        tuxsuite bake submit tux.json
      env:
        TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}

